### ISSUE TITLE
Cells doesn't work with Rails 3.0.x

### ISSUE THREAD

**Issue by romul** [trailblazer/cells#108]
I get following error:

```
/home/roman/.rvm/gems/ree-1.8.7-2011.12/gems/railties-3.0.10/lib/rails/paths.rb:16:in `method_missing': undefined method `existent_directories' for #<Rails::Paths::Path:0xcf09838> (NoMethodError)
from /home/roman/.rvm/gems/ree-1.8.7-2011.12/gems/cells-3.8.2/lib/cells/engines.rb:58:in `append_engine_view_path!'
from /home/roman/.rvm/gems/ree-1.8.7-2011.12/gems/cells-3.8.2/lib/cells/engines.rb:46:in `append_engines_view_paths_for'
from /home/roman/.rvm/gems/ree-1.8.7-2011.12/gems/cells-3.8.2/lib/cells/engines.rb:46:in `each'
from /home/roman/.rvm/gems/ree-1.8.7-2011.12/gems/cells-3.8.2/lib/cells/engines.rb:46:in `append_engines_view_paths_for'
from /home/roman/.rvm/gems/ree-1.8.7-2011.12/gems/cells-3.8.2/lib/cells/railtie.rb:16
```

P.S. Patch will be coming soon...
